const name = prompt ("Please enter your name")
const welcome = `¡welcome ${name}! `
alert(welcome);
const election = prompt ("see apartments :\n1. New 1\n2 used");{
if (eletion === "1") {
    console.log("User chose new apartments");
  } else if (eleccion === "2") {
    console.log("User chose used apartments");
  } else {
    console.log("Invalid election");
 }
}{
if (eletion === "1") {
    const price = parseFloat(prompt("Price of the new house: $250.000.000"));
    const profit = price * 0.2; // 20%
}   } {
    if (eletion === "2") {
        const price = parseFloat(prompt("Price of used house: $170,000,000"));
        const profit = price * 0.1; // 10%
}   }   
const bye = (`¡See you later ${name}!`)